### ISSUE TITLE
Update to more recent language and core versions

### ISSUE THREAD

**Issue by abingham** [Fresheyeball/elm-chartjs#6]
Do you have plans to update this package to work on elm 0.16.0 and core 3.0.0?

**Comment by abingham** [comment]
[This branch on my fork](https://github.com/abingham/elm-chartjs/tree/version-upgrade) _seems_ to work with elm-0.16.0 and core-3.0.0. But I'm still enough of an elm newb that I may have missed something important. In particular, I'm sure the `elm-package.json` could use some work.

**Comment by Fresheyeball** [comment]
can you submit those changes as a pull request?
