### ISSUE TITLE
Chart re-rendering too often

### ISSUE THREAD

**Issue by abingham** [Fresheyeball/elm-chartjs#7]
It seems that elm-chartjs is causing the chart to completely re-render on each construction of the view. That is, in my view function I create chart. Even if none of the arguments to the `chart` call changes, I still see a full re-rendering of the chart, as evidenced by the re-execution of the animation on the chart. 

This is really problematic since certain parts of the my model are updated as the user types individual keystrokes; each keystroke triggers a call to `view` and, thus, a re-rendering of the chart. Besides being annoying, this eventually just overwhelms the browser tab and I have to kill it.

I'm a bit new to elm so I'm guessing, but perhaps the problem is how `newElement` is being used. That is, perhaps the elm runtime can't figure out that it doesn't need to actually replace the DOM elements for most of the calls. I'm not sure, though.

Is there any way to fix this problem?

**Comment by Fresheyeball** [comment]
The easiest way I can see would be to use `Html.Lazy.lazy` somewhere in your code.

**Comment by abingham** [comment]
Ah, that's definitely seem to fix things. Thanks!
